version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here
      - CHROME_PROFILE_PATH=/tmp/chrome_profile
    volumes:
      - chrome_data:/tmp/chrome_profile
      - session_data:/tmp/whatsapp_sessions
    restart: unless-stopped

  # Optional: Add Redis for session storage
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  chrome_data:
  session_data: