services:
  - type: web
    name: django-docker-app
    runtime: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: SECRET_KEY
        value: django-insecure-80yor-n0%#gp5!n+os(f%e(x)_44l$#3p04vcn49qaj&r9nb!f
      - key: DEBUG
        value: False